# Generated by Django 4.2.7 on 2023-11-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=256)),
                ('numero_ruc', models.CharField(max_length=11)),
                ('tipo_contribuyente', models.CharField(max_length=256)),
                ('tipo_actividad', models.CharField(max_length=256)),
                ('nombre_comercial', models.CharField(max_length=256)),
                ('direccion_fiscal', models.CharField(max_length=256)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(max_length=256)),
                ('dni', models.CharField(max_length=32)),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=256)),
                ('categoria', models.CharField(max_length=256)),
                ('cantidad', models.CharField(max_length=2)),
                ('tamaño', models.CharField(max_length=256)),
                ('forma', models.CharField(max_length=32, null=True)),
                ('precio', models.CharField(max_length=32)),
                ('material', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEntregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto_entregado', models.CharField(max_length=256)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('estado_de_entrega', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=256)),
                ('precio', models.CharField(max_length=32)),
                ('duracion', models.CharField(max_length=32)),
                ('lugar_servicio', models.CharField(max_length=256)),
            ],
        ),
    ]
