# Generated by Django 4.2.7 on 2023-11-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(max_length=256)),
                ('dni', models.CharField(max_length=32)),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=256)),
                ('categoria', models.CharField(max_length=256)),
                ('cantidad', models.CharField(max_length=2)),
                ('tamaño', models.CharField(max_length=256)),
                ('forma', models.CharField(max_length=32, null=True)),
                ('precio', models.CharField(max_length=32)),
                ('material', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(max_length=256)),
                ('tipo_pedido', models.CharField(max_length=256)),
                ('lugar', models.CharField(max_length=256)),
                ('tipo_envio', models.CharField(max_length=256)),
                ('direccion_pedido', models.CharField(max_length=256)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
